name: rx-angular CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true
  NX_DISTRIBUTED_TASK_EXECUTION: true
  NX_VERBOSE_LOGGING: false

jobs:
  agents:
    runs-on: ubuntu-latest

    name: Agent 1
    timeout-minutes: 20

    strategy:
      matrix:
        agent: [1, 2, 3]

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup

      - name: Start Nx Agent ${{ matrix.agent }}
        run: yarn nx-cloud start-agent

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup

      - run: yarn nx-cloud start-ci-run

      - name: Run Affected lint
        run: yarn nx affected:lint --parallel --maxParallel=3

      - name: Run Affected test
        run: yarn nx affected:test --parallel --maxParallel=3

      - name: Run Affected e2e
        run: yarn nx affected:e2e

      # don't run build in parallel, can cause dead locks
      - name: Run Affected build
        run: yarn nx affected:build --parallel=false

      - run: yarn nx-cloud stop-all-agents

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
